// import mongoose from 'mongoose';

// // --- 1. Schema for a single quiz item ---
// // This strictly enforces the structure generated by the Gemini LLM.
// const quizItemSchema = new mongoose.Schema({
//     question: { 
//         type: String, 
//         required: true 
//     },
//     options: { 
//         type: [String], // Array of strings for the multiple-choice options
//         required: true,
//         // Optional validation to ensure it's an array of strings
//         validate: [v => Array.isArray(v) && v.every(i => typeof i === 'string'), 'Options must be an array of strings.']
//     },
//     answer: { 
//         type: String, 
//         required: true // The correct answer string
//     },
// }, { _id: false }); // We don't need IDs for nested items

// // --- 2. Main Schema for the uploaded document record ---
// const documentSchema = new mongoose.Schema({
//     // Fields captured from the request body
//     subject: {
//         type: String,
//         required: [true, 'Subject is required for the document.'],
//         trim: true,
//     },
//     // Filename reported by the Python service
//     filename: {
//         type: String,
//         required: [true, 'Filename is required.'],
//         trim: true,
//     },
//     // The core data: an array of structured quiz items
//     quiz_data: {
//         type: [quizItemSchema], 
//         required: [true, 'Quiz data is required.']
//     },
    
//     // Metadata
//     processed_at: {
//         type: Date,
//         default: Date.now,
//     },
// }, { timestamps: true });

// // --- 3. Export the Model ---
// const Document = mongoose.model('Document', documentSchema);

// export default Document;